-- AlterTable
ALTER TABLE "Prompt" ALTER COLUMN "tagId" SET NOT NULL,
ALTER COLUMN "tagId" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "Prompt" ADD CONSTRAINT "Prompt_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
